// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachSpark.Web.Data;

#nullable disable

namespace TeachSpark.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250624233719_UpdateWorksheetTemplateStructure")]
    partial class UpdateWorksheetTemplateStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.AcademicStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeLevelExpectation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedGraduate1")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedGraduate2")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedGraduate3")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedGraduate4")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreparedGraduate5")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Standard")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subheading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GleCode");

                    b.HasIndex("Subject", "Grade");

                    b.ToTable("AcademicStandards");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedIpAddresses")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthlyRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scopes")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyValue")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApiUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostIncurred")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ResponseTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("RequestedAt");

                    b.ToTable("ApiUsages");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeLevel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("School")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.BloomLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionVerbs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Examples")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Order")
                        .IsUnique();

                    b.ToTable("BloomLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionVerbs = "define, duplicate, list, memorize, recall, repeat, reproduce, state, identify, name, recognize, select, match",
                            ColorCode = "#6f42c1",
                            Description = "Retrieving, recognizing, and recalling relevant knowledge from long-term memory",
                            Examples = "Define literary terms, list character names, recall plot events",
                            Name = "Remember",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionVerbs = "classify, describe, discuss, explain, express, identify, indicate, locate, recognize, report, restate, review, select, translate, paraphrase, summarize",
                            ColorCode = "#0d6efd",
                            Description = "Constructing meaning from oral, written, and graphic messages",
                            Examples = "Explain theme, summarize plot, describe character traits",
                            Name = "Understand",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionVerbs = "apply, carry out, demonstrate, dramatize, employ, illustrate, interpret, operate, practice, schedule, sketch, solve, use, write, implement",
                            ColorCode = "#198754",
                            Description = "Carrying out or using a procedure through executing or implementing",
                            Examples = "Apply grammar rules, use literary devices, implement writing strategies",
                            Name = "Apply",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ActionVerbs = "analyze, appraise, calculate, categorize, compare, contrast, criticize, differentiate, discriminate, distinguish, examine, experiment, question, test, deconstruct",
                            ColorCode = "#fd7e14",
                            Description = "Breaking material into constituent parts and determining how parts relate to each other",
                            Examples = "Compare characters, analyze author's purpose, examine text structure",
                            Name = "Analyze",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            ActionVerbs = "appraise, argue, assess, attach, choose, compare, defend, estimate, judge, predict, rate, select, support, value, evaluate, critique",
                            ColorCode = "#dc3545",
                            Description = "Making judgments based on criteria and standards through checking and critiquing",
                            Examples = "Critique author's argument, evaluate source credibility, judge character decisions",
                            Name = "Evaluate",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            ActionVerbs = "arrange, assemble, collect, compose, construct, create, design, develop, formulate, manage, organize, plan, prepare, propose, set up, write, generate",
                            ColorCode = "#20c997",
                            Description = "Putting elements together to form a coherent or functional whole; reorganizing into a new pattern",
                            Examples = "Write alternative ending, create character analysis, design presentation",
                            Name = "Create",
                            Order = 6
                        });
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.CommonCoreStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleActivities")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CommonCoreStandards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Key Ideas and Details",
                            Code = "CCSS.ELA-LITERACY.RL.8.1",
                            Description = "Cite the textual evidence that most strongly supports an analysis of what the text says explicitly as well as inferences drawn from the text.",
                            Domain = "Reading: Literature",
                            Grade = "8",
                            IsActive = true,
                            SortOrder = 1,
                            Subject = "English Language Arts"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Key Ideas and Details",
                            Code = "CCSS.ELA-LITERACY.RL.8.2",
                            Description = "Determine a theme or central idea of a text and analyze its development over the course of the text, including its relationship to the characters, setting, and plot.",
                            Domain = "Reading: Literature",
                            Grade = "8",
                            IsActive = true,
                            SortOrder = 2,
                            Subject = "English Language Arts"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Key Ideas and Details",
                            Code = "CCSS.ELA-LITERACY.RL.8.3",
                            Description = "Analyze how particular lines of dialogue or incidents in a story or drama propel the action, reveal aspects of a character, or provoke a decision.",
                            Domain = "Reading: Literature",
                            Grade = "8",
                            IsActive = true,
                            SortOrder = 3,
                            Subject = "English Language Arts"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Text Types and Purposes",
                            Code = "CCSS.ELA-LITERACY.W.8.1",
                            Description = "Write arguments to support claims with clear reasons and relevant evidence.",
                            Domain = "Writing",
                            Grade = "8",
                            IsActive = true,
                            SortOrder = 4,
                            Subject = "English Language Arts"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Conventions of Standard English",
                            Code = "CCSS.ELA-LITERACY.L.8.1",
                            Description = "Demonstrate command of the conventions of standard English grammar and usage when writing or speaking.",
                            Domain = "Language",
                            Grade = "8",
                            IsActive = true,
                            SortOrder = 5,
                            Subject = "English Language Arts"
                        });
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.Worksheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcademicStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessibilityOptions")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BloomLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommonCoreStandardId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GenerationCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("GenerationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAnswerKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmModel")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderedHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Warnings")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorksheetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcademicStandardId");

                    b.HasIndex("BloomLevelId");

                    b.HasIndex("CommonCoreStandardId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Worksheets");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.WorksheetExport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorksheetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorksheetId");

                    b.ToTable("WorksheetExports");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.WorksheetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPromptTemplate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPromptTemplate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorksheetTemplates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApiKey", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApiUsage", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.ApiKey", "ApiKey")
                        .WithMany("ApiUsages")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.Worksheet", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.AcademicStandard", "AcademicStandard")
                        .WithMany("Worksheets")
                        .HasForeignKey("AcademicStandardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeachSpark.Web.Data.Entities.BloomLevel", "BloomLevel")
                        .WithMany("Worksheets")
                        .HasForeignKey("BloomLevelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeachSpark.Web.Data.Entities.CommonCoreStandard", "CommonCoreStandard")
                        .WithMany("Worksheets")
                        .HasForeignKey("CommonCoreStandardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeachSpark.Web.Data.Entities.WorksheetTemplate", "Template")
                        .WithMany("Worksheets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", "User")
                        .WithMany("Worksheets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicStandard");

                    b.Navigation("BloomLevel");

                    b.Navigation("CommonCoreStandard");

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.WorksheetExport", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.Worksheet", "Worksheet")
                        .WithMany("Exports")
                        .HasForeignKey("WorksheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worksheet");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.WorksheetTemplate", b =>
                {
                    b.HasOne("TeachSpark.Web.Data.Entities.ApplicationUser", "User")
                        .WithMany("WorksheetTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.AcademicStandard", b =>
                {
                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApiKey", b =>
                {
                    b.Navigation("ApiUsages");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("WorksheetTemplates");

                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.BloomLevel", b =>
                {
                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.CommonCoreStandard", b =>
                {
                    b.Navigation("Worksheets");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.Worksheet", b =>
                {
                    b.Navigation("Exports");
                });

            modelBuilder.Entity("TeachSpark.Web.Data.Entities.WorksheetTemplate", b =>
                {
                    b.Navigation("Worksheets");
                });
#pragma warning restore 612, 618
        }
    }
}
